### PR TITLE
licensing-permisssions-update

### PR DESCRIPTION
**Pull request by marcin-ozog**

### CODE REVIEW

**Comment by siddarthpatel** [comment]
@marcin-ozog Could you please add your changes to add authorization here as well:
https://github.com/IBM/ibm-commonui-operator/blob/master/pkg/resources/utils.go#L506
https://github.com/IBM/ibm-commonui-operator/blob/master/pkg/resources/utils.go#L644
https://github.com/IBM/ibm-commonui-operator/blob/master/deploy/olm-catalog/ibm-commonui-operator/1.6.0/ibm-commonui-operator.v1.6.0.clusterserviceversion.yaml#L386

**Comment by marcin-ozog** [comment]
@siddarthpatel sure - updated, thank you.

**Review by siddarthpatel — APPROVED** [review]

**Pull request merged**
